/* bremen — Typecast 배역 내레이션 (tools/typecast/gen_tale.py가 voice_script.json에서 생성, 손으로 고치지 말 것) */
const NARRATION_CLIPS = {
 "옛날 옛날, 방앗간에 늙은 당나귀가 살았어요.": "audio/tc/bremen/nar_cad6f2eebf.mp3",
 "당나귀를 톡 눌러 봐요!": "audio/tc/bremen/nar_b05564e7de.mp3",
 "당나귀를 톡!": "audio/tc/bremen/nar_ceb014d880.mp3",
 "당나귀는 오랫동안 무거운 곡식 자루를 날랐어요. 이제는 힘이 없어요.": "audio/tc/bremen/nar_d628608d1f.mp3",
 "주인: \"이제 일을 못 하겠구나. 너를 내보내야겠다.\"": "audio/tc/bremen/miller_51eb296a0f.mp3",
 "당나귀: \"괜찮아! 브레멘에 가서 음악가가 될 거야!\"": "audio/tc/bremen/donkey_a268521ba6.mp3",
 "당나귀가 길을 가는데, 덤불이 흔들흔들.": "audio/tc/bremen/nar_550eda1b58.mp3",
 "덤불 뒤에서 멍멍! 누구일까요?": "audio/tc/bremen/nar_530b224d16.mp3",
 "멍멍 하고 우는 친구는 누굴까? 다시 들어 봐요.": "audio/tc/bremen/nar_daa787587e.mp3",
 "야옹 하고 우는 친구는 누굴까? 다시 들어 봐요.": "audio/tc/bremen/nar_397e43792c.mp3",
 "꼬끼오 하고 우는 친구는 누굴까? 다시 들어 봐요.": "audio/tc/bremen/nar_bf77e1e089.mp3",
 "당나귀예요! 반짝이는 친구를 눌러 봐요!": "audio/tc/bremen/nar_a23d0c5e78.mp3",
 "강아지예요! 반짝이는 친구를 눌러 봐요!": "audio/tc/bremen/nar_0da4388365.mp3",
 "고양이예요! 반짝이는 친구를 눌러 봐요!": "audio/tc/bremen/nar_d215c6f27a.mp3",
 "닭이에요! 반짝이는 친구를 눌러 봐요!": "audio/tc/bremen/nar_28b432c7f4.mp3",
 "강아지가 헉헉, 혀를 쭉 내밀었어요.": "audio/tc/bremen/nar_b6333f5775.mp3",
 "강아지: \"늙어서 사냥을 못 한다고 내보내졌어요.\"": "audio/tc/bremen/dog_e36fa6ef50.mp3",
 "당나귀: \"그럼 우리 같이 브레멘에 가서 음악가가 되자!\"": "audio/tc/bremen/donkey_86be83eedc.mp3",
 "담장 위에서 야옹~ 누구일까요?": "audio/tc/bremen/nar_5fe93c97f0.mp3",
 "수염이 축 처진 고양이예요. \"쥐를 못 잡는다고 내보내졌어.\"": [
  "audio/tc/bremen/nar_3aacc17ba1.mp3",
  "audio/tc/bremen/cat_692fbbefbb.mp3"
 ],
 "강아지: \"우리랑 같이 가자! 브레멘에서 노래하자!\"": "audio/tc/bremen/dog_93923866c7.mp3",
 "지붕 위에서 꼬끼오! 누구일까요?": "audio/tc/bremen/nar_0c1fe2d9bb.mp3",
 "닭: \"이제 나는 필요 없대. 꼬끼오…\"": "audio/tc/bremen/rooster_fba6bccb72.mp3",
 "당나귀: \"우리랑 음악대 하자! 네 목소리 최고야!\"": "audio/tc/bremen/donkey_803719bc60.mp3",
 "당나귀, 강아지, 고양이, 닭. 네 친구가 모였어요!": "audio/tc/bremen/nar_db2e35d274.mp3",
 "길가 풀밭에서 노래 연습을 해요. 당나귀가 먼저 들려줄게요. 잘 듣고 똑같이 톡톡!": "audio/tc/bremen/nar_e2995821a6.mp3",
 "이번엔 세 개! 잘 들어 봐요.": "audio/tc/bremen/nar_c4fce59b53.mp3",
 "마지막 노래예요. 잘 들어 봐요.": "audio/tc/bremen/nar_48a70a9f94.mp3",
 "이제 똑같이 톡톡!": "audio/tc/bremen/nar_e6b656725a.mp3",
 "하하, 새 노래가 됐네! 한 번 더!": "audio/tc/bremen/nar_4ee9cd4293.mp3",
 "처음은 누구 소리였지?": "audio/tc/bremen/nar_cdc679b42f.mp3",
 "다음은 누구 소리였지?": "audio/tc/bremen/nar_cfb9d4a23e.mp3",
 "멍멍, 야옹! 잘했어요!": "audio/tc/bremen/nar_d1f8596cff.mp3",
 "히힝, 멍멍, 꼬끼오! 멋진 노래예요!": "audio/tc/bremen/nar_2f1e8ff8fa.mp3",
 "야옹, 꼬끼오, 히힝! 최고의 음악대예요!": "audio/tc/bremen/nar_d6b342313c.mp3",
 "해가 지고 캄캄한 숲이 되었어요. 부엉이가 부엉부엉.": "audio/tc/bremen/nar_b5bad09ad6.mp3",
 "숲을 지나가요. 옆으로 쓱 밀어 줘요!": "audio/tc/bremen/nar_41de1234bf.mp3",
 "옆으로 쓱! 숲을 지나가요.": "audio/tc/bremen/nar_be70714d25.mp3",
 "닭이 나무 꼭대기로 푸드덕 올라갔어요.": "audio/tc/bremen/nar_a6eba6cb2a.mp3",
 "닭: \"저기 불빛이 보여요! 집이 있어요!\"": "audio/tc/bremen/rooster_bbbcd6c399.mp3",
 "불빛이 새어 나오는 창문이에요. 그런데 너무 높아서 아무도 안 닿아요.": "audio/tc/bremen/nar_426c584f4e.mp3",
 "서로 등에 올라서 탑을 쌓아요! 크고 무거운 친구가 맨 아래예요.": "audio/tc/bremen/nar_3cc057c0e6.mp3",
 "누가 맨 아래에 설까요?": "audio/tc/bremen/nar_0b9716a150.mp3",
 "맨 꼭대기는 누구?": "audio/tc/bremen/nar_de1a151938.mp3",
 "당나귀 등에는 누가 올라갈까요?": "audio/tc/bremen/nar_f68b0a6f5b.mp3",
 "강아지 등에는 누가 올라갈까요?": "audio/tc/bremen/nar_5fc53a2953.mp3",
 "강아지: \"아이고, 무거워! 나는 위로 갈래~\"": "audio/tc/bremen/dog_c3cee40d65.mp3",
 "고양이: \"아이고, 무거워! 나는 위로 갈래~\"": "audio/tc/bremen/cat_4a654474dc.mp3",
 "닭: \"아이고, 무거워! 나는 위로 갈래~\"": "audio/tc/bremen/rooster_a094653d8f.mp3",
 "흔들흔들! 더 크고 무거운 친구가 먼저예요.": "audio/tc/bremen/nar_e9abd0479a.mp3",
 "당나귀가 맨 아래! 튼튼해요.": "audio/tc/bremen/nar_ac0adcb647.mp3",
 "당나귀, 강아지, 고양이, 닭! 닭이 창문에 닿았어요!": "audio/tc/bremen/nar_094af7d55d.mp3",
 "창문 안을 들여다보니, 도둑 셋이 금화를 세며 맛있는 걸 먹고 있어요.": "audio/tc/bremen/nar_c319b33c71.mp3",
 "도둑: \"금화가 잔뜩이다! 하하하!\"": "audio/tc/bremen/boss_05a808a786.mp3",
 "닭: \"우리 음악을 크게 들려주자!\"": "audio/tc/bremen/rooster_0bd4569254.mp3",
 "다 같이 목청껏! 톡톡톡 눌러서 노래해요!": "audio/tc/bremen/nar_d51a4428d7.mp3",
 "탑을 톡톡톡! 더 크게 노래해요!": "audio/tc/bremen/nar_bdac4df89b.mp3",
 "도둑들은 \"괴물이다!\" 하고 숲으로 후다닥 달아났어요.": [
  "audio/tc/bremen/nar_278cbeef9d.mp3",
  "audio/tc/bremen/robber_8255dc9e60.mp3",
  "audio/tc/bremen/nar_f2560e9def.mp3"
 ],
 "네 친구는 남은 음식을 냠냠 먹고, 불을 끄고 잠이 들었어요.": "audio/tc/bremen/nar_09b4a9d2d5.mp3",
 "한밤중, 도둑 하나가 살금살금 돌아왔어요. 쉿!": "audio/tc/bremen/nar_eae11ae849.mp3",
 "아궁이 안에서 뭔가 반짝! 톡 눌러 봐요.": "audio/tc/bremen/nar_2edc6b1930.mp3",
 "도둑: \"앗, 따가워! 불씨인 줄 알았는데!\"": "audio/tc/bremen/robber_33d5d455d7.mp3",
 "문 앞에 또 반짝! 톡 눌러 봐요.": "audio/tc/bremen/nar_581a1b4ed4.mp3",
 "도둑: \"아얏! 다리를 콕 찔렸어!\"": "audio/tc/bremen/robber_64cec0ba3e.mp3",
 "짚더미에도 반짝! 톡 눌러 봐요.": "audio/tc/bremen/nar_b91a282cea.mp3",
 "도둑: \"으악! 누가 쿵 찼어!\"": "audio/tc/bremen/robber_789853bfc7.mp3",
 "저 위 들보에서도 반짝! 톡 눌러 봐요.": "audio/tc/bremen/nar_a5e7dc3b06.mp3",
 "도둑: \"살려 줘~!\"": "audio/tc/bremen/robber_21efb8de0c.mp3",
 "도둑: \"그 집엔 귀신이 할퀴고, 누가 다리를 콕 찌르고, 거인이 쿵 차고, 지붕에선 재판관이 도둑 잡아라! 소리쳤어!\"": "audio/tc/bremen/robber_5fd158fbf5.mp3",
 "사실은 고양이, 강아지, 당나귀, 닭이었는데 말이에요! 도둑들은 다시는 오지 않았어요.": "audio/tc/bremen/nar_02e8a664ef.mp3",
 "아침이 밝았어요. 네 친구는 이 집이 참 좋았어요.": "audio/tc/bremen/nar_19ca137af0.mp3",
 "\"브레멘은 못 갔지만, 여기가 우리 집이야!\"": "audio/tc/bremen/donkey_af002efbcd.mp3",
 "당나귀는 마당 짚더미, 강아지는 문 앞, 고양이는 아궁이, 닭은 지붕 위. 톡톡 눌러서 마음껏 연주해요!": "audio/tc/bremen/nar_1335b1e736.mp3",
 "함께라서 행복한 브레멘 음악대였답니다.": "audio/tc/bremen/nar_aa1a739e0f.mp3"
};
const VOICE_LINES = {
 "cut_monster": [
  "audio/tc/bremen/robber_45db2e0931.mp3",
  "audio/tc/bremen/boss_cb245afc93.mp3"
 ],
 "cut_ghost": "audio/tc/bremen/robber_929ba45b45.mp3"
};
